feat(eslint): add Testing Library plugin for ESLint
sumup-oss/foundry pull request #244
Opened 2021-03-26 18:48 UTC by larimaza

## Purpose

Add [Testing Library plugin for ESLint](https://github.com/testing-library/eslint-plugin-testing-library), extending their Recommended and React configurations.

This is so that projects that use this library (such as SumUp's Partner Portal) can get better linter feedback.

Please advise, I'm not sure if I added everything correctly!

## Definition of done

- [x] Development completed
- [x] Reviewers assigned
- [x] Unit and integration tests

2021-03-26 18:51 UTC, larimaza commented
Should I sign the contributor agreement or just be added as a member?

2021-03-26 19:42 UTC, connor-baer commented
@larimaza You're already a member :) The bot isn't smart enough yet to know who's a SumUp employee. [Contributions to teaching it](https://github.com/sumup/oss-clark) are welcome 😄

No need to sign unless you want to.

2021-03-26 19:46 UTC, connor-baer commented
@larimaza Regarding the failing tests: can you make sure you're using the required version of Node ([v10.x](https://github.com/sumup-oss/foundry/blob/main/.nvmrc)) and run the tests again, please?

2021-03-26 20:32 UTC, connor-baer requested changes
Thank you so much for this fantastic contribution! 🙌🏻

2021-03-26 20:32 UTC, connor-baer commented on src/configs/eslint/config.ts
> +    },
The `extends` and `plugins` options only should/need to apply to spec files, could you move them into the `overrides`, please?

Looking at the existing configs, I realized that they were suboptimal as well, so I've opened a PR (https://github.com/sumup-oss/foundry/pull/245) to fix them, too.

2021-03-29 13:59 UTC, larimaza commented on src/configs/eslint/config.ts
> +    },
Ooh, THAT'S what `overrides` is for! 😅

2021-03-30 14:52 UTC, connor-baer approved these changes
✨

2021-04-28 14:23 UTC, merged